[book]
title = "Rust棒棒哒（资源大全中文版）"
authors = ["zzy"]
description = "Rust棒棒哒, Rust资源大全, Rust资源大全中文版）"
language = "zh"
src = "src"
multilingual = true

[build]
build-dir = "docs"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/zzy/awesome-rust-zh-cn"
# default-theme = "rust"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
